version: '3.4'

services:
    app:
        image: travelto
        container_name: travelto_CI
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 3000:80